packages:
  - bundles/**

ignoredBuiltDependencies:
  - '@serialport/bindings-cpp'
  - '@vaadin/vaadin-usage-statistics'
  - esbuild
  - iframe-resizer

onlyBuiltDependencies:
  - '@serialport/bindings-cpp'
  - '@vaadin/vaadin-usage-statistics'
  - better-sqlite3
  - esbuild
  - iframe-resizer
  - unrs-resolver
  - vuex-module-decorators
