packages:
  - bundles/**

allowBuilds:
  '@parcel/watcher': true
  '@serialport/bindings-cpp': true
  '@vaadin/vaadin-usage-statistics': true
  better-sqlite3: true
  core-js-pure: true
  msgpackr-extract: true
  unrs-resolver: true
  vuex-module-decorators: true
