packages:
  - bundles/**

ignoredBuiltDependencies:
  - '@serialport/bindings-cpp'
  - '@vaadin/vaadin-usage-statistics'
  - esbuild
  - iframe-resizer

onlyBuiltDependencies:
  - '@ffprobe-installer/darwin-arm64'
  - '@parcel/watcher'
  - '@serialport/bindings-cpp'
  - '@vaadin/vaadin-usage-statistics'
  - better-sqlite3
  - esbuild
  - iframe-resizer
  - msgpackr-extract
  - unrs-resolver
  - vuex-module-decorators
